#!/bin/bash
set -eo pipefail

function log() {
	echo "--> $1"
}

log "Shell provisioner will run in 15s"
sleep 15

log "Upgrading all packages"
sudo yum upgrade -y

log "Installing ansible"
sudo yum install -y ansible

cd /tmp/ansible

log "Running ansible playbook"
# ansible will make the sudo on it's own

if curl -s http://169.254.169.254/latest/ --max-time 1 &> /dev/null; then
	echo "EC2 instance detected, installing with ec2-cloud role additions"
	cloud="True"
else
	cloud="False"
fi

ansible-playbook -i localhost_inventory common.yml \
  --connection=local --extra-vars "is_ec2=$cloud"

log "Removing /tmp/ansible"
rm -rf /tmp/ansible