#!/bin/bash
set -eo pipefail

function log() {
	echo "--> $1"
}

log "Shell provisioner will run in 15s"
sleep 15

#log "Updating all packages" && true || yum update -y
log "Installing ansible"
sudo yum install -y ansible

cd /tmp/ansible

log "Running ansible playbook"
ansible-playbook -i localhost_inventory common.yml --connection=local

log "Removing /tmp/ansible"
rm -rf /tmp/ansible