- name: install basic packages
  yum: pkg={{item}} state=installed
  with_items:
    - gcc
    - make
    - git
    - mercurial
    - wget
    - curl
    - nc
    - unzip
    - tcpdump
    - openssl-devel
    - gcc-c++
    - golang
    - tmux
    - zsh
    - unzip
    - python-pip
    - rpm-build
    - bind-utils
    - tree
    - nano
    - rsync

- name: Install latest docker from binary
  get_url:
    url: "https://get.docker.io/builds/Linux/x86_64/docker-latest"
    dest: /usr/local/bin/docker
    mode: 0755

- name: Linking docker to /usr/bin
  file:
    state: link
    src: /usr/local/bin/docker
    dest: /usr/bin/docker
    mode: 0755

- name: Copy docker unit
  copy: src=system/docker.service dest=/etc/systemd/system/docker.service

- name: Enable docker on boot
  service: name=docker.service enabled=yes state=started

- name: Pulling vlipco/hull into docker
  command: /usr/local/bin/docker pull vlipco/hull

- name: "Create extra convention dirs"
  file: path={{ item }} state=directory
  with_items:
     - /usr/local/rc
     - /srv

- name: Installing motd
  copy: src=conf/motd dest=/etc/motd
  tags: motd

- name: Creating sshd.service configuration folder
  file: state=directory path=/etc/systemd/system/sshd.service.d

- name: Installing sshd post stop command in /etc/systemd/system/sshd.service.d
  copy: src=conf/sshd-stop.conf dest=/etc/systemd/system/sshd.service.d/stop.conf

- name: Installg profile.d path-additions
  copy: src=bin/path-additions.sh dest=/etc/profile.d/path-additions.sh mode=0755

- name: Creating vlipco.target for systemd
  copy: src=system/vlipco.target dest=/etc/systemd/system/vlipco.target

- name: Enabling vlipco.target on boot
  service: name=vlipco.target enabled=yes state=started

- name: Finding local user to be managed
  filter: 
    items: "{{managed_users}}"
    test: "id __item__ &> /dev/null"
    fact: target_users

- name: Creating rc.local script
  copy: src=bin/rc-local.sh dest=/etc/rc.d/rc.local mode=0755

- name: Copying rc-local.service definition
  copy: src=system/rc-local.service dest=/etc/systemd/system/rc-local.service

- name: Enabling rc-local service unit
  command: /usr/bin/systemctl enable /etc/systemd/system/rc-local.service

- name: Starting rc-local service
  service: name=rc-local state=started
