- name: Checking consul version
  shell: /usr/bin/consul -v | /usr/bin/grep -q v0.4.0
  register: consul_installed
  ignore_errors: True

- name: Downloading Consul 0.4
  when: consul_installed | failed
  get_url:
    url: "https://dl.bintray.com/mitchellh/consul/0.4.0_linux_amd64.zip"
    dest: /tmp/0.4.0_linux_amd64.zip
    sha256sum: 4f8cd1cc5d90be9e1326fee03d3c96289a4f8b9b6ccb062d228125a1adc9ea0c

- name: Unarchiving consul
  when: consul_installed | failed
  #uses -0 to overwrite and avoid queries
  command: unzip -o /tmp/0.4.0_linux_amd64.zip chdir=/tmp

- name: Installing Consul
  when: consul_installed | failed
  command: mv /tmp/consul /usr/bin/consul

- name: Copying systemd units
  copy: "src=system/consul.service dest=/etc/systemd/system/consul.service"

- name: Enabling units
  service: "name=consul.service enabled=yes"

- name: Updating systemd daemon
  command: "/usr/bin/systemctl daemon-reload"

- name: Restarting units
  command: "/usr/bin/systemctl restart consul.service"


