- name: Cloning Yadr in users homes
  with_items: target_users
  git:
    depth: 1
    repo: git://github.com/davidpelaez/yadr.git
    dest: "~{{item}}/.yadr"
    version: minimal

- name: Installing Yadr for target users
  shell: "cd ~{{item}}/.yadr && HOME=~{{item}} bash -l -c '/usr/local/bin/rake install'"
  with_items: target_users

- name: Installing vundle...be patient
  with_items: target_users
  shell: 'cd ~{{item}}/.yadr && HOME=~{{item}} /usr/local/bin/vim --noplugin -u vim/vundles.vim -N "+set hidden" "+syntax on" +BundleClean! +BundleInstall +qall'

- name: Changing ownership of all files in users home
  with_items: target_users
  command: "/usr/bin/zsh -l -c 'cd ~{{item}} && chown {{item}} -R $(ls -A)'"

- name: Making zsh default shell for users
  command: /usr/bin/env chsh -s /bin/zsh {{item}}
  with_items: target_users